### ISSUE TITLE
What’s the license of that code?

### ISSUE THREAD

**Issue by pagiraud** [diddledani/twitodon#17]
Is this app FOSS? If yes, what is the license?

**Comment by lucyllewy** [comment]
Hi, sorry about the confusion. I wasn't anticipating this gaining so much traction in such a short period of time - especially while I'm at the Ubuntu Summit - I've now added a LICENSE file and ensured the marked license in `package.json` is correct.

For the avoidance of doubt the license is GPLv3 or later.
