### ISSUE TITLE
IPv6 not supported at your hosting - fails to resolve domain.

### ISSUE THREAD

**Issue by ddowse** [diddledani/twitodon#28]
When I tried to sign-in on my IPv6 only mastodon instance it fails with this error message: 

`{"statusCode":500,"code":"ENOTFOUND","error":"Internal Server Error","message":"request to https://mastodon.noreboot.org/api/v1/apps failed, reason: getaddrinfo ENOTFOUND mastodon.noreboot.org"}`

Please enable IPv6 on your hosting environment to resolve AAAA Records. 

Thanks a lot

**Comment by lucyllewy** [comment]
This should be fixed now. I've had to move the site to a different location.
