### ISSUE TITLE
Privacy policy on twitodon?

### ISSUE THREAD

**Issue by janngobble** [diddledani/twitodon#6]
There’s no privacy policy attached to the website running the application.
Is there one?

Thanks!

Jann

**Comment by lucyllewy** [comment]
Yes there is:

![image](https://user-images.githubusercontent.com/147548/198998780-44f27614-34d1-4a9c-949f-f575c89d6878.jpeg)

**Comment by janngobble** [comment]
I'm Sorry, I worded it wrong. Does twitodon sell or protected us against our "links" or "handles" and their associations from being sold or used for any other purpose than linking us to our followers/followed? That's what I meant.

**Comment by lucyllewy** [comment]
For the avoidance of doubt, Twitodon does not (i.e. I do not) sell any data nor make any data available to third parties. I've added this extra detail to the `privacy.html` page which will go live shortly, once the automated build and deployment has succeeded.

**Comment by janngobble** [comment]
Thank you so much!
