### ISSUE TITLE
some dummy input filtering

### ISSUE THREAD

**Issue by wchristian** [diddledani/twitodon#7]
i'm a dummy and pasted https://mastodon.social/@Mithaldu instead of https://mastodon.social/

might wanna just remove trailing @ stuff to help folks like me? :)

Edit by Dani: Also need to forcibly add `https://` if there is no protocol specified

**Comment by lucyllewy** [comment]
Thanks for reporting this issue. I'll try to get it fixed as soon as I can. Unfortunately I'm quite busy till Friday next week preparing for and attending the Ubuntu summit
